<?php

namespace Jamesjjt\PhpFpl\Dto;

use Jamesjjt\PhpFpl\Contracts\DtoContract;

class PlayerFullDto implements DtoContract
{
    public function __construct(
        public bool $can_transact,
        public bool $can_select,
        public ?float $chance_of_playing_next_round,
        public ?float $chance_of_playing_this_round,
        public int $code,
        public int $cost_change_event,
        public int $cost_change_event_fall,
        public float $cost_change_start,
        public int $cost_change_start_fall,
        public int $dreamteam_count,
        public int $element_type,
        public string $ep_next,
        public string $ep_this,
        public int $event_points,
        public string $first_name,
        public string $form,
        public int $id,
        public bool $in_dreamteam,
        public string $news,
        public ?string $news_added,
        public int $now_cost,
        public string $photo,
        public string $points_per_game,
        public bool $removed,
        public string $second_name,
        public string $selected_by_percent,
        public bool $special,
        public ?int $squad_number,
        public string $status,
        public int $team,
        public int $team_code,
        public int $total_points,
        public int $transfers_in,
        public int $transfers_in_event,
        public int $transfers_out,
        public int $transfers_out_event,
        public string $value_form,
        public string $value_season,
        public string $web_name,
        public ?string $region,
        public ?string $team_join_date,
        public int $minutes,
        public int $goals_scored,
        public int $assists,
        public int $clean_sheets,
        public int $goals_conceded,
        public int $own_goals,
        public int $penalties_saved,
        public int $penalties_missed,
        public int $yellow_cards,
        public int $red_cards,
        public int $saves,
        public int $bonus,
        public int $bps,
        public string $influence,
        public string $creativity,
        public string $threat,
        public string $ict_index,
        public int $starts,
        public string $expected_goals,
        public string $expected_assists,
        public string $expected_goal_involvements,
        public string $expected_goals_conceded,
        public int $influence_rank,
        public int $influence_rank_type,
        public int $creativity_rank,
        public int $creativity_rank_type,
        public int $threat_rank,
        public int $threat_rank_type,
        public int $ict_index_rank,
        public int $ict_index_rank_type,
        public ?int $corners_and_indirect_freekicks_order,
        public string $corners_and_indirect_freekicks_text,
        public ?int $direct_freekicks_order,
        public string $direct_freekicks_text,
        public ?int $penalties_order,
        public string $penalties_text,
        public float $expected_goals_per_90,
        public float $saves_per_90,
        public float $expected_assists_per_90,
        public float $expected_goal_involvements_per_90,
        public float $expected_goals_conceded_per_90,
        public float $goals_conceded_per_90,
        public int $now_cost_rank,
        public int $now_cost_rank_type,
        public int $form_rank,
        public int $form_rank_type,
        public int $points_per_game_rank,
        public int $points_per_game_rank_type,
        public int $selected_rank,
        public int $selected_rank_type,
        public float $starts_per_90,
        public float $clean_sheets_per_90
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            $data['can_transact'],
            $data['can_select'],
            $data['chance_of_playing_next_round'],
            $data['chance_of_playing_this_round'],
            $data['code'],
            $data['cost_change_event'],
            $data['cost_change_event_fall'],
            $data['cost_change_start'],
            $data['cost_change_start_fall'],
            $data['dreamteam_count'],
            $data['element_type'],
            $data['ep_next'],
            $data['ep_this'],
            $data['event_points'],
            $data['first_name'],
            $data['form'],
            $data['id'],
            $data['in_dreamteam'],
            $data['news'],
            $data['news_added'],
            $data['now_cost'],
            $data['photo'],
            $data['points_per_game'],
            $data['removed'],
            $data['second_name'],
            $data['selected_by_percent'],
            $data['special'],
            $data['squad_number'],
            $data['status'],
            $data['team'],
            $data['team_code'],
            $data['total_points'],
            $data['transfers_in'],
            $data['transfers_in_event'],
            $data['transfers_out'],
            $data['transfers_out_event'],
            $data['value_form'],
            $data['value_season'],
            $data['web_name'],
            $data['region'],
            $data['team_join_date'],
            $data['minutes'],
            $data['goals_scored'],
            $data['assists'],
            $data['clean_sheets'],
            $data['goals_conceded'],
            $data['own_goals'],
            $data['penalties_saved'],
            $data['penalties_missed'],
            $data['yellow_cards'],
            $data['red_cards'],
            $data['saves'],
            $data['bonus'],
            $data['bps'],
            $data['influence'],
            $data['creativity'],
            $data['threat'],
            $data['ict_index'],
            $data['starts'],
            $data['expected_goals'],
            $data['expected_assists'],
            $data['expected_goal_involvements'],
            $data['expected_goals_conceded'],
            $data['influence_rank'],
            $data['influence_rank_type'],
            $data['creativity_rank'],
            $data['creativity_rank_type'],
            $data['threat_rank'],
            $data['threat_rank_type'],
            $data['ict_index_rank'],
            $data['ict_index_rank_type'],
            $data['corners_and_indirect_freekicks_order'],
            $data['corners_and_indirect_freekicks_text'],
            $data['direct_freekicks_order'],
            $data['direct_freekicks_text'],
            $data['penalties_order'],
            $data['penalties_text'],
            $data['expected_goals_per_90'],
            $data['saves_per_90'],
            $data['expected_assists_per_90'],
            $data['expected_goal_involvements_per_90'],
            $data['expected_goals_conceded_per_90'],
            $data['goals_conceded_per_90'],
            $data['now_cost_rank'],
            $data['now_cost_rank_type'],
            $data['form_rank'],
            $data['form_rank_type'],
            $data['points_per_game_rank'],
            $data['points_per_game_rank_type'],
            $data['selected_rank'],
            $data['selected_rank_type'],
            $data['starts_per_90'],
            $data['clean_sheets_per_90']
        );
    }
}
